services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-guias
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  guias-service:
    build:
      context: .
      dockerfile: dockerfile
    container_name: guias-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ORACLE_DB_URL: ${ORACLE_DB_URL}
      ORACLE_DB_USERNAME: ${ORACLE_DB_USERNAME}
      ORACLE_DB_PASSWORD: ${ORACLE_DB_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  guias-bff:
    build:
      context: ./guias-bff
      dockerfile: Dockerfile
    container_name: guias-bff
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
