spring.application.name=guias-bff
server.port=8081

spring.rabbitmq.host=rabbitmq-guias
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

rabbitmq.cola.guias=guias.cola
rabbitmq.cola.creacion-guias=guias.creacion.cola
rabbitmq.cola.errores=guias.errores.cola
rabbitmq.exchange.guias=guias.exchange
rabbitmq.routing-key.creacion-guias=guias.creacion.routingkey
rabbitmq.routing-key.guias=guias.routingkey
rabbitmq.routing-key.errores=guias.errores.routingkey

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://duocazureva.b2clogin.com/5d3fcce5-e142-4263-9331-422b98a2a19a/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://duocazureva.b2clogin.com/duocazureva.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_duocdemoazure_registro_login
