spring.application.name=guias

spring.datasource.url=jdbc:h2:mem:guiasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

efs.ruta=./efs/guias
aws.region=us-east-1
aws.s3.bucket=bucket-duoc-s3

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://duocazureva.b2clogin.com/5d3fcce5-e142-4263-9331-422b98a2a19a/v2.0/
spring.security.oauth2.resourceserver.jwt.audiences=c91fdfe2-a82f-4154-afda-113cfc6ebac9